[package]
name = "mk"
version = "0.1.0"
edition = "2018"
authors = ["AcrylicShrimp <led789zxpp@naver.com>"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
res = { path = "../res", features = ["reader"] }
